blank_issues_enabled: true
contact_links:
  - name: Xavfsizlik muammosi
    url: https://github.com/ElyorErgashov2010/DownloadHelper/security
    about: Ehtimoliy xavfsizlik muammosini public Issue orqali yozmang.
